"""followers:

Revision ID: 967219a07755
Revises: df5723f5eb9b
Create Date: 2019-03-06 17:47:06.968323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967219a07755'
down_revision = 'df5723f5eb9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
